### Mage Knight Solo plays
GET {{base-url}}/plays/duponter/mksolo

### Shelves Bareelstraat
GET {{base-url}}/session/play?collections=mine,wouteraerts,jarrebesetoert&bestWith=3

### Shelves Forum Mortsel
GET {{base-url}}/session/play?collections=mine,bartie,svennos&bestWith=3
